name: xUnit.net CI Build
on:
  push:
    branches:
      - main
      - 'rel/**'
  workflow_dispatch:

jobs:
  build:
    name: "CI Build"
    runs-on: ubuntu-22.04
    env:
      DOTNET_NOLOGO: true
    steps:
      - name: Clone source
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.x
            7.0.x

      - name: Get .NET information
        run: dotnet --info

      - name: "Build target: CI"
        env:
          SIGN_APP_ID: ${{ secrets.SIGN_APP_ID }}
          SIGN_APP_SECRET: ${{ secrets.SIGN_APP_SECRET }}
          SIGN_CERT_NAME: ${{ secrets.SIGN_CERT_NAME }}
          SIGN_SUBSCRIPTION: ${{ secrets.SIGN_SUBSCRIPTION }}
          SIGN_TENANT: ${{ secrets.SIGN_TENANT }}
          SIGN_VAULT_URI: ${{ secrets.SIGN_VAULT_URI }}
        run: dotnet run --project tools/builder --no-launch-profile -- CI --timing

      - name: "Upload artifact: test"
        uses: actions/upload-artifact@v3.1.1
        with:
          name: test
          path: artifacts/test
        if: always()

      - name: "Upload artifact: packages"
        uses: actions/upload-artifact@v3.1.1
        with:
          name: packages
          path: artifacts/packages
        if: always()
